//
// Created by a2685 on 2024/4/12.
//

#ifndef REPLACE_WITH_YOUR_PROJECT_NAME_BACKGROUND_BGM_HPP
#define REPLACE_WITH_YOUR_PROJECT_NAME_BACKGROUND_BGM_HPP


class background_bgm {

};


#endif //REPLACE_WITH_YOUR_PROJECT_NAME_BACKGROUND_BGM_HPP
