//
// Created by Yihss on 2024/4/24.
//

#ifndef REPLACE_WITH_YOUR_PROJECT_NAME_GRAYGUNTOWER_HPP
#define REPLACE_WITH_YOUR_PROJECT_NAME_GRAYGUNTOWER_HPP


class grayguntower {

};


#endif //REPLACE_WITH_YOUR_PROJECT_NAME_GRAYGUNTOWER_HPP
