//
// Created by Yihss on 2024/3/1.
//

#ifndef REPLACE_WITH_YOUR_PROJECT_NAME_TIMERECORD_HPP
#define REPLACE_WITH_YOUR_PROJECT_NAME_TIMERECORD_HPP


class Timerecord {

};


#endif //REPLACE_WITH_YOUR_PROJECT_NAME_TIMERECORD_HPP
